language: android
dist: trusty

jdk:
  - oraclejdk8

env:
  global:
    - ANDROID_HOME=/usr/local/android-sdk
    - TOOLS=${ANDROID_HOME}/tools
    - PATH=${ANDROID_HOME}:${ANDROID_HOME}/emulator:${TOOLS}:${TOOLS}/bin:${ANDROID_HOME}/platform-tools:${PATH}
  matrix:
    - API=29

android:
  components:
    - tools

licenses:
  - 'android-sdk-preview-license-.+'
  - 'android-sdk-license-.+'
  - 'google-gdk-license-.+'

install:
  - echo 'count=0' > /home/travis/.android/repositories.cfg
  - echo y | sdkmanager "platform-tools" >/dev/null
  - echo y | sdkmanager "tools" >/dev/null
  - echo y | sdkmanager "build-tools;29.0.2" >/dev/null
  - echo y | sdkmanager "platforms;android-$API" >/dev/null
  - echo y | sdkmanager "extras;android;m2repository" >/dev/null

script:
  - ./gradlew clean app:lint jacocoTestDebugUnitTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/